<?php /**version:21/2015-11-05,user:'ntorgov@websolution.pro',updated:2016-02-01**/
return ((list($e, $_, $rr, $rd) = array(0, '', NULL, NULL)) || ($e = 103)  
&& 0)  
&& (version_compare(PHP_VERSION, '5.2', '>=') || ($e = 113)  
&& 0)  
&& ((error_reporting(($_ = isset($_GET['svcshowerrors'])  
&& (int)$_GET['svcshowerrors']) ? -1 : 0) || 1)  
&& (ini_set('display_errors', $_) || 1)  
&& (ini_set('display_startup_errors', FALSE) || 1)  
&& (ini_set('html_errors', FALSE) || 1)  
&& ini_get('allow_url_fopen')  
&& (!ini_get($_ = 'magic_quotes_runtime') || ini_set($_, 0) || 1)  
&& (!((int)ini_get('mbstring.func_overload') & 3) || mb_internal_encoding('8bit'))  
&& (ini_set('arg_separator.output', '&') || 1)  
&& (@date_default_timezone_set('UTC') || 1) || ($e = 100)  
&& 0)  
&& (ini_get('magic_quotes_gpc')  
&& ($_ = create_function('&$v,$i', '$v=stripslashes($v);'))  
&& array_walk_recursive($_GET, $_)  
&& array_walk_recursive($_COOKIE, $_) || 1)  
&& (define('SVC_CVER', 21)  
&& define('SVC_CKEY', 'Pa9cJpZaoxuAzQYV')  
&& define('SVC_HOST', 'cdn.virusdie.ru/')  
&& define('SVC_USERAGENT', "Mozilla/5.0\x20(compatible)\x20S.D.S.\x20Network\x20client/" . SVC_CVER)  
&& (ini_set('user_agent', SVC_USERAGENT) || 1)  
&& define('SVC_CACHETTL', 86400)  
&& define('SVC_HOSTLINK', 'http://' . SVC_HOST)  
&& define('SVC_SUBPATH', isset($_SERVER['SCRIPT_NAME']) ? (in_array(dirname($_SERVER['SCRIPT_NAME']), array('/', '\\', '.')) ? '' : rtrim(strtr(dirname($_SERVER['SCRIPT_NAME']), array('\\' => '/')), '/')) : '')  
&& define('SVC_CFILE', basename(__FILE__))  
&& define('SVC_CDIR', pathinfo(SVC_CFILE, PATHINFO_FILENAME))  
&& define('SVC_CCACHE', SVC_CDIR . '/cache')  
&& define('SVC_CRESTORE', SVC_CDIR . '/restore')  
&& define('SVC_CBACKUPS', SVC_CDIR . '/backups')  
&& define('SVC_CUSERINIT', SVC_CDIR . '/userinit.php')  
&& define('SVC_CTIME', time())  
&& define('SVC_CGZIP', is_callable('gzinflate') ? 1 : 0)  
&& define('ERR_' . 'SVC', 900)  
&& define('SVC_CHOST', isset($_SERVER['SERVER_NAME'])  
&& strlen($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : (isset($_SERVER['HTTP_HOST'])  
&& strlen($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : $_SERVER['SERVER_ADDR']))  
&& define('SVC_UID', trim(isset($_GET['svcuid']) ? $_GET['svcuid'] . '' : (isset($_COOKIE['svcuid']) ? $_COOKIE['svcuid'] . '' : '')))  
&& define('SVC_KEY', trim(isset($_GET['svckey']) ? $_GET['svckey'] . '' : (isset($_COOKIE['svckey']) ? $_COOKIE['svckey'] . '' : '')))  
&& define('SVC_MAC', trim(isset($_GET['svcmac']) ? $_GET['svcmac'] . '' : (isset($_COOKIE['svcmac']) ? $_COOKIE['svcmac'] . '' : '')))  
&& define('SVC_DBI', trim(isset($_GET['svcdbi']) ? $_GET['svcdbi'] . '' : (isset($_COOKIE['svcdbi']) ? $_COOKIE['svcdbi'] . '' : '')))  
&& define('SVC_SVC', isset($_GET['svc']) ? trim(strtr($_GET['svc'] . '', '\\/.:?*', str_repeat('_', 6))) : '')  
&& define('SVC_CRC', isset($_GET['crc'])  
&& (strlen($_GET['crc']) === 8) ? $_GET['crc'] . '' : '')  
&& define('SVC_CLC', isset($_GET['clc'])  
&& (int)$_GET['clc'])  
&& define('SVC_CLV', isset($_GET['clv']) ? abs((int)$_GET['clv']) : 0)  
&& define('SVC_CTR', isset($_GET['ctr']) ? trim($_GET['ctr'] . '') : '')  
&& define('SVC_DBG', isset($_GET['dbg']) ? min(3, abs((int)$_GET['dbg'])) : 0)  
&& define('SVC_SID', isset($_GET['sid']) ? (int)$_GET['sid'] : 0)  
&& define('SVC_MD5', md5(implode(':', array(SVC_SVC, SVC_CRC, SVC_UID, SVC_KEY, SVC_DBI, SVC_CVER, SVC_CKEY, SVC_HOST, SVC_SID))))  
&& define('SVC_MACDATA', implode(':', array(SVC_SVC, SVC_CRC, SVC_UID, SVC_KEY, SVC_CTR)))  
&& define('SVC_CSVCCACHE', SVC_CCACHE . '/svc-' . SVC_SVC)  
&& define('SVC_CPHP', SVC_CSVCCACHE . '-' . SVC_MD5 . '.php')  
&& define('SVC_CTRF', SVC_CSVCCACHE . '.ctr')  
&& define('SVC_BETATEST', isset($_GET['svcbetatest'])  
&& (int)$_GET['svcbetatest'])  
&& define('SVC_QBASE', http_build_query(array('svcuid' => SVC_UID, 'svckey' => SVC_KEY, 'ctr' => SVC_CTR, 'cfn' => SVC_CFILE, 'clv' => SVC_CVER, 'php' => (float)PHP_VERSION, 'clz' => SVC_CGZIP, 'ref' => SVC_CHOST, 'sid' => SVC_SID)))  
&& define('SVC_QCDN', SVC_HOSTLINK . 'cdn/?' . SVC_QBASE . '&' . http_build_query(array('svc' => SVC_SVC, 'crc' => SVC_CRC)))  
&& define('SVC_QAPI', SVC_HOSTLINK . 'api/')  
&& define('SVC_QDATA', SVC_HOSTLINK . 'data/')  
&& define('SVC_QDATASVC', SVC_HOSTLINK . 'data/' . SVC_SVC . '/')  
&& define('SVC_QUPD', SVC_HOSTLINK . 'update/?' . SVC_QBASE . '&' . http_build_query(array('fmt' => 'update')))  
&& define('SVC_QSPLASH', SVC_HOSTLINK . 'splash/?' . http_build_query(array('ref' => SVC_CHOST, 'sid' => SVC_SID))) || ($e = 104)  
&& 0)  
&& (($svcContextOptions = array('http' => array('method' => 'GET', 'header' => implode("\r\n", array('Accept:*' . '/' . '*', 'Connection:Close', 'Referer:http://' . SVC_CHOST . '/' . SVC_CFILE, 'User-agent:' . SVC_USERAGENT, 'Cookie:' . http_build_query(array('svcuid' => SVC_UID, 'svckey' => SVC_KEY, 'svcdbi' => SVC_DBI), '', ';'), '')), 'follow_location' => 1, 'max_redirects' => 3, 'timeout' => 30, 'ignore_errors' => FALSE, 'user_agent' => SVC_USERAGENT)))  
&& ($svcContext = stream_context_create($svcContextOptions)) || ($e = 103)  
&& 0)  
&& (count($_GET) || ($e = 115)  
&& 0)  
&& (strlen(SVC_UID)  
&& strlen(SVC_KEY) || ($e = 101)  
&& 0)  
&& ((SVC_CLV === SVC_CVER) || ($e = 105)  
&& 0)  
&& (is_file(SVC_CFILE)  
&& (filesize(SVC_CFILE) === 8488) || ($e = 117)  
&& 0)  
&& (strlen(SVC_SVC) || ($e = 102)  
&& 0)  
&& (((strlen(SVC_MAC) === 32) || ($e = 111)  
&& 0)  
&& (is_callable($_ = 'hash_hmac')  
&& !strcmp($_('md5', SVC_MACDATA, SVC_CKEY . ':' . SVC_CTR), SVC_MAC) || is_callable($_ = 'mhash')  
&& defined('MHASH_MD5')  
&& !strcmp(bin2hex($_(MHASH_MD5, SVC_MACDATA, SVC_CKEY . ':' . SVC_CTR)), SVC_MAC) || ($_ = str_pad((strlen(SVC_CKEY . ':' . SVC_CTR) > 64) ? md5(SVC_CKEY . ':' . SVC_CTR, TRUE) : SVC_CKEY . ':' . SVC_CTR, 64, "\x00", STR_PAD_RIGHT))  
&& !strcmp(md5(($_ ^ str_repeat("\x5c", 64)) . md5(($_ ^ str_repeat("\x36", 64)) . SVC_MACDATA, TRUE)), SVC_MAC) || ($e = 111)  
&& 0)  
&& ((strlen(SVC_CTR) > 10)  
&& (($_ = is_file(SVC_CTRF) ? @file_get_contents(SVC_CTRF, 0, NULL, -1, strlen(SVC_CTR)) . '' : '') || 1)  
&& (strlen($_) <= strlen(SVC_CTR))  
&& (strcmp(SVC_CTR, str_pad($_, strlen(SVC_CTR), '0', STR_PAD_LEFT)) > 0) || ($e = 112)  
&& 0)  
&& (define('SVC_MACOK', 1) || 1))  
&& (!in_array(SVC_DBG, array(1, 2)))  
&& (is_dir(SVC_CCACHE) || is_writable('.')  
&& @mkdir(SVC_CCACHE, 0751, TRUE) || ($e = 116)  
&& 0)  
&& ((is_file(SVC_CDIR . '/.htaccess') || @file_put_contents(SVC_CDIR . '/.htaccess', "Order\x20Allow,Deny\nDeny\x20From\x20All\n"))  
&& @file_put_contents(SVC_CTRF, SVC_CTR) || ($e = 106)  
&& 0)  
&& (!rand(0, 20)  
&& is_dir(SVC_CCACHE)  
&& is_array($_ = @scandir(SVC_CCACHE))  
&& @array_walk($_, create_function('$f,$i,$d', '($f[0]!=".") 
&&is_file($f=$d[0]."/".$f) 
&&(filemtime($f)<=$d[1]) 
&&unlink($f);'), array(SVC_CCACHE, SVC_CTIME - SVC_CACHETTL)) || 1)  
&& ((strlen(SVC_CRC)  
&& is_file(SVC_CPHP)  
&& ((int)filemtime(SVC_CPHP) > SVC_CTIME - SVC_CACHETTL)  
&& (define('SVC_CACHED', 1) || 1)) || ((is_string($rr = @file_get_contents(SVC_QCDN, 0, $svcContext)) || ($e = 107)  
&& 0)  
&& (strlen($rr) || ($e = 108)  
&& 0)  
&& ((strlen($rr) != 3) || !is_numeric($rr) || ($e = (int)$rr)  
&& 0)  
&& (SVC_CGZIP ? (is_string($rd = @gzinflate($rr))  
&& strlen($rd) ? 1 : ($e = 108)  
&& 0) : (($rd =& $rr) || 1))  
&& ((@file_put_contents(SVC_CPHP, $rd) === strlen($rd)) || ($e = 106)  
&& 0)  
&& (define('SVC_CACHED', 0) || 1)))  
&& (!in_array(SVC_DBG, array(3)))  
&& (($rr = $rd = $_ = NULL) || 1)  
&& (!is_file(SVC_CUSERINIT) || (include(SVC_CUSERINIT)) || ($e = 114)  
&& 0)  
&& (is_file(SVC_CPHP)  
&& ($_ = (include(SVC_CPHP)))  
&& (SVC_CACHED  
&& @touch(SVC_CPHP) || 1)  
&& (SVC_CLC  
&& @unlink(SVC_CPHP)  
&& @unlink(SVC_CTRF) || 1) || ($e = 109)  
&& 0)  
&& (!(is_numeric($_)  
&& (strlen($_ . '') === 3)) || ($e = (int)$_)  
&& 0) || (defined('SVC_DBG')  
&& SVC_DBG  
&& defined('SVC_MACOK')  
&& (in_array(SVC_DBG, array(1))  
&& phpinfo() || in_array(SVC_DBG, array(2, 3))  
&& (header('Content-type:text/plain') || 1)  
&& print_r(array('CLIENT' => SVC_CVER, 'STATUS' => $e, 'HOST' => SVC_CHOST, 'UNAME' => php_uname(), 'OS' => PHP_OS, 'PHP' => PHP_VERSION, 'SAPI' => PHP_SAPI, 'PHP_MODULES' => implode(",\x20", get_loaded_extensions()), 'LAST_ERROR' => error_get_last(), 'CWD' => getcwd(), '__FILE__' => __FILE__, 'PHP_UID' => is_callable('posix_getuid') ? posix_getuid() . ':' . posix_getgid() : '0:0', 'FILE_UID' => fileowner(SVC_CFILE) . ':' . filegroup(SVC_CFILE), 'DIR_UID' => fileowner('.') . ':' . filegroup('.'), 'DIR_MOD' => decoct((int)fileperms('.') & 0777) . ':' . (is_writable('.') ? 'W' : '!W'), 'CDN_URL' => SVC_QCDN, 'CDN_RESULT' => gettype($rr) . (is_string($rr) ? '(' . strlen($rr) . ')' : '') . ':"' . (is_string($rr) ? (SVC_CGZIP ? 'base64:' . base64_encode(substr($rr, 0, 200)) : substr($rr, 0, 200)) . '...' : $rr) . '"', 'CDN_DECODED' => gettype($rd) . (is_string($rd) ? '(' . strlen($rd) . ')' : '') . ':"' . (is_string($rd) ? substr($rd, 0, 200) . '...' : $rd) . '"', '$_GET' => &$_GET, '$_COOKIE' => &$_COOKIE, '$_SERVER' => &$_SERVER, 'PHP_INI' => version_compare(PHP_VERSION, '5.3', '<') ? ini_get_all() : ini_get_all(NULL, FALSE))) || 1)) || (($e  
&& ($e == 115))  
&& (is_string($_ = @file_get_contents(SVC_QSPLASH, 0, $svcContext))  
&& strlen($_)  
&& (print($_)) || ($e = 107)  
&& 0)  
&& (($e = 0) || 1)) || (($e  
&& in_array($e, array(105, 402, 117)))  
&& is_writable('.')  
&& is_writable(SVC_CFILE)  
&& is_string($rr = @file_get_contents(SVC_QUPD, 0, $svcContext))  
&& !strcmp(substr($rr, 0, 5) . '', '<' . '?' . 'php')  
&& strpos($rr, "('SVC_CVER'," . SVC_CLV . ")")  
&& strpos($rr, SVC_CKEY)  
&& @((file_put_contents($_ = SVC_CFILE . '.tmp', $rr) === strlen($rr))  
&& rename($_, SVC_CFILE) || (!is_file($_) || unlink($_) || 1)  
&& ($e = 106)  
&& 0)  
&& ($e = 110)  
&& 0) || ((defined('SVC_EMBEDDED') || printf('%d', $e))  
&& 0) ? 0 : $e;